---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  attributes:
    apt:
      compile_time_update: true
      confd:
        install_recommends: false

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: debian-8.5
    run_list:
      - recipe[apt::default]

suites:
  - name: chef12package
    driver:
      require_chef_omnibus: 12.21.4
    run_list:
      - recipe[duosec::default]

  - name: chef13package
    driver:
      require_chef_omnibus: 13.3.42
    run_list:
      - recipe[duosec::default]
