---
<%
  duounix_ikey = ENV['DUOUNIX_IKEY'] || 'ikey-default'
  duounix_skey = ENV['DUOUNIX_SKEY'] || 'skey-default'
  duounix_host = ENV['DUOUNIX_HOST'] || 'host-default'
  duounix_test_user = ENV['DUOUNIX_TEST_USER'] || 'testuser'
  duounix_test_user_ssh_key = ENV['DUOUNIX_TEST_USER_SSH_KEY'] || ''
%>
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

verifier:
  name: inspec

provisioner:
  name: dokken
  data_bags_path: test/data_bags
  attributes:
    apt:
      compile_time_update: true
      confd:
        install_recommends: false

platforms:
  - name: ubuntu14
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: ubuntu16
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian8
    driver:
      image: debian:8.9
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: centos6
    driver:
      image: centos:6.9
      pid_one_command: /sbin/init
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which curl

  - name: centos7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: fedora28
    driver:
      image: fedora:28
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: amazon
    driver:
      image: amazonlinux:2018.03
      pid_one_command: /sbin/init
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which

  - name: amazon2
    driver:
      image: amazonlinux:2
      pid_one_command: /usr/lib/systemd/systemd
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which

suites:
  - name: chef13
    verifier:
      inspec_tests:
        - test/smoke/default
    driver:
      chef_version: 13.9.4
    run_list:
      - recipe[duounix_test::default]
    attributes:
      duounix_wrapper:
        test_user: <%= duounix_test_user %>
        test_user_ssh_pub_key: <%= duounix_test_user_ssh_key %>
        config:
          ikey: <%= duounix_ikey %>
          skey: <%= duounix_skey %>
          host: <%= duounix_host %>

  - name: chef13databag
    verifier:
      inspec_tests:
        - test/smoke/default
    driver:
      chef_version: 13.9.4
    run_list:
      - recipe[duounix_test::default]
    attributes:
      duounix_wrapper:
        data_bag:
          enable: true
        test_user: <%= duounix_test_user %>
        test_user_ssh_pub_key: <%= duounix_test_user_ssh_key %>
