---
<%
  duounix_ikey = ENV['DUOUNIX_IKEY'] || ''
  duounix_skey = ENV['DUOUNIX_SKEY'] || ''
  duounix_host = ENV['DUOUNIX_HOST'] || ''
  duounix_test_user = ENV['DUOUNIX_TEST_USER'] || ''
  duounix_test_user_ssh_key = ENV['DUOUNIX_TEST_USER_SSH_KEY'] || ''
%>
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  attributes:
    apt:
      compile_time_update: true
      confd:
        install_recommends: false

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: debian-8.5
    run_list:
      - recipe[apt::default]

suites:
  - name: chef13
    verifier:
      inspec_tests:
        - test/smoke/default
    driver:
      require_chef_omnibus: 13.3.42
    run_list:
      - recipe[duounix_test::default]
    attributes:
      duounix_wrapper:
        test_user: <%= duounix_test_user %>
        test_user_ssh_pub_key: <%= duounix_test_user_ssh_key %>
        config:
          ikey: <%= duounix_ikey %>
          skey: <%= duounix_skey %>
          host: <%= duounix_host %>

  - name: chef13databag
    verifier:
      inspec_tests:
        - test/smoke/default
    driver:
      require_chef_omnibus: 13.3.42
    run_list:
      - recipe[duounix_test::default]
    attributes:
      duounix_wrapper:
        data_bag:
          enable: true
        test_user: <%= duounix_test_user %>
        test_user_ssh_pub_key: <%= duounix_test_user_ssh_key %>
